# The sensor sensor-controller configmap includes configuration information for the sensor sensor-controller
apiVersion: v1
kind: ConfigMap
metadata:
  name: sensor-sensor-controller-configmap
data:
  config: |
    instanceID: axis
